services:
  web:
    build:
      context: ../../
      dockerfile: infra/docker/web.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
    depends_on:
      - api

  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "4000:4000"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # futuros serviços para evolução de microsserviços:
  # node-service:
  # go-service:
  # kotlin-service:

volumes:
  postgres_data:
